### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ghost** [Spooghetti420/kurt3#1]
how would we use this?

**Comment by Spooghetti420** [comment]
This is a good point, I will be updating the readme soon to give some examples, since when I made it, I didn't know what I wanted the API to look like, exactly.
The basic structure looks like this, though:
```
from kurt3.project import Project
with Project("project_file_name.sb3") as project:
    project.get_sprite_by_name("Sprite1").add_costume("test/projects/assets/Bread.svg", "Bread1")
    project.get_sprite_by_name("Sprite2").add_block(GoToXY(10, 10))
    project.save("output_file_name.sb3")
```
A good deal of features are still missing, such as support for most types of block. I am still thinking of a solution for certain problems I'm having with creating certain kinds of blocks, but hopefully I will be able to get some work done on the rest of the API soon. :) There is also no good way to add sprites to the project atm, so very sorry if you were planning on using it soon.

**Comment by Spooghetti420** [comment]
You may also gain some insight on how to use it by checking out what autocompletes you get from using it in an IDE. I've done my best to write documentation within the code itself, at least, so hopefully its purpose should be clear. The main methods you might use are probably on the `Project` class, or its property `targets` (represents the sprites and the stage). Many of the attributes on the different objects are also settable, for example a sprite's name.

**Comment by ghost** [comment]
Thank you! This'd be really helpfull for my mass audio uploader project I'm trying to make!
